[client]
showSidebarNavigation = true

[global]
dataFrameSerialization = "legacy"

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "localhost"

[server]
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200

[logger]
level = "info"
messageformat = "%(asctime)s %(message)s"
datetimeFormat = "%Y-%m-%d %H:%M:%S"

[client]
toolbarMode = "developer" # "viewer" is another option. Default is "developer"

# Use this to set the Python version
[runtime]
python = "3.11" 