[client]
showSidebarNavigation = true
toolbarMode = "developer" # "viewer" is another option. Default is "developer"

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "localhost"

[server]
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200

[logger]
level = "info"

[runtime]
python = "3.11"